# Installation of numpy & Jupyter Notebook

In [ ]:
# to install numpy--> pip install numpy
# to install jupyter notebook --> pip install jupyter

# to open that folder --> go to the folder location in command prompt --> jupyter notebook

In [1]:
# to check version of numpy
# as refers to alias which means it allows alternet name to refer same thing.

import numpy as np

print(np.__version__)

1.22.3


# Array Creation numpy

In [2]:
#creating arrays

import numpy as np

arr = np.array([10,20,30,50,60])
#arr = np.array((1,2,3,4,5))

print(arr)
print(type(arr))  #print the type of object passed in it

[10 20 30 50 60]
<class 'numpy.ndarray'>


In [4]:
#array dimensions
# 1. 0-D array 
# 2. 1-D array 
# 3. 2-D array 
# 4. 3-D array 

arr0 = np.array(20)
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr3 = np.array([  [[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]  ])

print(arr0)
print(arr1)
print(arr2)
print(arr3)

20
[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [6]:
#to check dimension of array we use ndim attributes

print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


# Accessing items

In [7]:
#Accessing array elements

arr1 = np.array([1,2,3,4])

print(arr1[2]) # to print 3rd element

3


In [12]:
# Accessing elements in 2-D array
# print last element of 2nd array
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

print(arr2[1,3]) 

#using negative index

print("using negative index ",arr2[-1,-1])


8
using negative index  8


In [23]:
# Accessing elements in 3-D array
# print third element of the second array of the first array:

arr3 = np.array([  [[1,2,3],[4,5,6]]  ,  [[10,20,30],[40,50,60]]  ])

print(arr3[1,0,2])

#using negative index

print("using negative index ",arr3[-1,-2,-1])

#slicing
print("Slicing ",arr3[1,0,0:2])


30
using negative index  30
Slicing  [10 20]


# Slicing

In [21]:
# Array slicing

# slice --> [start:end] --> in that case step is consider as 1 by default
# [start:end:step] --> if need to apply step

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr[1,1:4])

print("Slicing using negative index ",arr[-2,-4:-1])

[6 7 8]
Slicing using negative index  [1 2 3]


In [27]:
# to check the data type of array --> dtype

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.dtype)

#adding element in the second array
arr[1,0] = 12
print(arr)

int32
[[ 1  2  3  4]
 [12  6  7  8]]


# Copy vs. View

In [30]:
# Copy vs. View
#copy --> create a new copy of array
#view --> its just a view of original array

arr = np.array([1,2,3,4])
#x = arr.copy()
x = arr.view()

arr[0] = 45

print(arr)
print(x)

[45  2  3  4]
[45  2  3  4]


# Array Shape

In [31]:
# Array shape
# to find the shape of array we use shape attribute method

arr_s = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_s.shape)


(2, 4)


# Reshape

In [32]:
# Array Reshape
# it means changing the shape of array

array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = array1.reshape(4,3) #reshape
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Array Iteration

In [5]:
# Iterating array
import numpy as np

arr1 = np.array([1,2,3,4]) # 1-D array

for x in arr1:
    print(x ,end=" ")

1 2 3 4 

In [6]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]]) # 2-D array

for x in arr2:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8


In [7]:
arr3 = np.array([  [[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]  ]) # 3-D array

for x in arr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
10
20
30
40
50
60


In [8]:
# we can use nditer() method as well.

arr3 = np.array([  [[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]  ]) # 3-D array

for x in np.nditer(arr3):
    print(x)


1
2
3
4
5
6
10
20
30
40
50
60


# Array Join

In [11]:
# Join --> merging two array
# we can use concatenate() or stack() function to join two array

#join 1-D array
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

newarr = np.concatenate((a1,a2))
print(newarr)

[1 2 3 4 5 6 7 8]


In [18]:
#join 2-D array

ar1 = np.array([[1,2,3,4],[5,6,7,8]])
ar2 = np.array([[9,10,11,12],[13,14,15,16]])

newarr1= np.concatenate((ar1,ar2) ,axis=1)
#print(newarr1)

#using stack function
newarr2 = np.stack((ar1,ar2))
print(newarr2)


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


# Array Split

In [21]:
# split array--> dividing array into multiple arrays

ar2 = np.array([[9,10,11,12],[13,14,15,16]])

new_arr = np.array_split(ar2,4)
print(new_arr)

[array([[ 9, 10, 11, 12]]), array([[13, 14, 15, 16]]), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32)]


# Array Search

In [26]:
# array search--> which returns the index number of perticular items

import numpy as np

arr = np.array([1,1,2,4,5,3,4,5,3,4])

x = np.where(arr==4)
print(x)
print(arr.dtype)



#to sort array we use sort() method
y = np.sort(arr)
print(y)

(array([3, 6, 9], dtype=int64),)
int32
[1 1 2 3 3 4 4 4 5 5]
